### ISSUE TITLE
code for ant and cheetah

### ISSUE THREAD

**Issue by zheshiyige** [jaesik817/bmaml_rl#2]
Hello,

           Could you also provide the code for the environment of ant and cheetah? Thank you!

**Comment by jaesik817** [comment]
Hi,

Thank you for your interesting on our project!!

Sure, will update the codes about the rest tasks.

BRs, Jaesik.

2019년 9월 21일 (토) 오전 6:43, zheshiyige <notifications@github.com>님이 작성:

**Comment by jsikyoon** [comment]
Hi,

I uploaded locomotion tasks and running script, 'running_scripts.txt'.

To run, you need to install mujoco env as mujoco-py instruction, https://github.com/openai/mujoco-py .

Thanks.

BRs, Jaesik.

**Comment by zheshiyige** [comment]
Hello,

         Thanks a lot for your help! Really appreciate for your time! One more question, in paper of Bayesian MAML, there are up to 200 meta iterations, but for original MAML paper, it only needs up to three gradient step. Could you tell me what is the difference here? Thank you!

**Comment by jsikyoon** [comment]
I am not sure what I understand is correct,

Meta iteration means learning iteration and three steps mean inner updates.

2019년 9월 26일 (목) 오후 10:39, zheshiyige <notifications@github.com>님이 작성:

**Comment by zheshiyige** [comment]
Got it, Thanks!
